version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
Enregistrez la configuration et voyez-la s'exécuter. Vous pouvez voir le résultat du travail dans l'application CircleCI.

Apprentissages